name: ci

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go mod download

      - run: go vet ./...

      - run: go build -v ./...

      - run: go test -v -coverprofile coverage.out ./...

      - name: upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: coverage.out
